### ISSUE TITLE
If you type "Functions", the program will crash.

### ISSUE THREAD

**Issue by tyrelsouza** [aaronchall/pythontrainer#2]
You prompt for "Functions, Exceptions, Keywords, Datatypes, or Modules" but the key is lowercase, maybe on trainer.py- line 17, force the key to be lower, or try except until you pass in a correct option.

**Comment by brettlangdon** [comment]
@tyrelsouza this appears to be resolved.

@aaronchall you can probably close this issue.

**Comment by tyrelsouza** [comment]
Fixed by https://github.com/aaronchall/pythontrainer/commit/c1ce73b9c950ecd60d701b78ee29369efe03429e
